# Generated by Django 4.1.4 on 2023-01-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_login_sys_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_login_sys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_f_name', models.CharField(max_length=50)),
                ('admin_l_name', models.CharField(max_length=50)),
                ('admin_email', models.EmailField(max_length=254)),
                ('admin_p_num', models.CharField(max_length=50)),
                ('admin_city', models.CharField(max_length=50)),
                ('admin_state', models.CharField(max_length=50)),
                ('admin_gender', models.CharField(max_length=50)),
                ('admin_image', models.ImageField(blank=True, null=True, upload_to='profile_pics')),
                ('admin_pass1', models.CharField(max_length=150)),
                ('admin_pass2', models.CharField(max_length=150)),
            ],
        ),
    ]
