# Generated by Django 4.1.4 on 2023-01-25 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_admin_login_sys'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50)),
                ('pcategory', models.CharField(max_length=50)),
                ('mrp', models.CharField(max_length=50)),
                ('dprice', models.CharField(max_length=50)),
                ('bname', models.CharField(max_length=50)),
                ('vender_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('p_image', models.ImageField(upload_to='P_images')),
            ],
        ),
    ]
