# Generated by Django 4.1.4 on 2023-01-28 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_product_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_details',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.login_sys'),
        ),
        migrations.AlterField(
            model_name='product_details',
            name='p_image',
            field=models.ImageField(blank=True, null=True, upload_to='P_images'),
        ),
    ]
