# Generated by Django 4.1.4 on 2023-01-28 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_product_details_user_alter_product_details_p_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_login_sys',
            name='admin_image',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='product_details',
            name='p_image',
            field=models.ImageField(blank=True, upload_to='P_images'),
        ),
    ]
