# Generated by Django 4.1.4 on 2023-01-28 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_product_details_p_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_sys',
            name='forget_password_token',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
