# Generated by Django 4.1.4 on 2023-01-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_login_sys_forget_password_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_sys',
            name='SuperUser',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
