# Generated by Django 4.1.4 on 2023-02-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_login_sys_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_login_sys',
            name='admin_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='profile_pics'),
        ),
    ]
